target:
  name: rockwell-automation
  platform: vdp
  disclosure: secure@ra.rockwell.com
  bounty: false
  program_url: https://www.rockwellautomation.com/en-us/capabilities/industrial-security.html
  domains:
  - rockwellautomation.com
  github_orgs: []
  excluded: []
